server:
  port: 7070

basePath:
  api: /bank/api
  index: /payment/api

setting:
  client: test
  secret: test

path:
  payment: http://localhost:7070/payment/api/index

bank:
  web:
    resources_path: ./src/resources/



